### ISSUE TITLE
Error: Testing requires the latest version of riscv/riscv/riscv-tools

### ISSUE THREAD

**Issue by yzhao30** [riscv/homebrew-riscv#24]
After I install the tool, I got error when running:

```
~ λ brew test riscv-tools
Error: Testing requires the latest version of riscv/riscv/riscv-tools
```
I also try to get the latest version

```
~ λ brew reinstall --build-from-source riscv-fesvr
```
and it says

```
Already on 'master'
Your branch is up to date with 'origin/master'.
```

Any clue to solve this?

**Comment by sbeamer** [comment]
I am unable to reproduce it. You can try removing the packages and re-installing them. When removing, you should remove them bottom up:

    brew remove riscv-tools riscv-pk riscv-gnu-toolchain riscv-isa-sim riscv-fesvr
