### ISSUE TITLE
pthread.cpp compile error  OSX 10.15.1 

### ISSUE THREAD

**Issue by JerryCui** [riscv/homebrew-riscv#28]
With latest version 

Got below error:
lib/posix/pthread.cpp:30:13: error: 'pthread_cond_init' was not declared in this scope; did you mean 'pthread_cond_t'?
   30 |     (void *)pthread_cond_init,

lib/posix/pthread.cpp:31:13: error: 'pthread_mutex_init' was not declared in this scope; did you mean 'pthread_mutex_t'?
   31 |     (void *)pthread_mutex_init,

lib/posix/pthread.cpp:32:13: error: 'pthread_self' was not declared in this scope; did you mean 'pthread_key_t'?
   32 |     (void *)pthread_self

**Comment by sbeamer** [comment]
The default build configuration is not expected to cross-compile to pthreads. We would welcome a contribution to add support for it.
