### ISSUE TITLE
An strange error occurred when I run riscv64-unknown-elf-gdb

### ISSUE THREAD

**Issue by PKUFlyingPig** [riscv/homebrew-riscv#37]
I installed the riscv-toolchain on my Mac followed the instruction in the README, it works well with qemu but when I run the riscv64-unknown-elf-gdb, an error occurred as follows:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/60659728/93464754-3dd52200-f91c-11ea-9359-7841fbbde9ae.png">
I cd into the /usr/local/Cellar/riscv-gnu-toolchain/master/share/ ,but don't find a file named gdb.
meantime, there is another error says
<img width="667" alt="image" src="https://user-images.githubusercontent.com/60659728/93464827-5f360e00-f91c-11ea-9ea5-d6fc9263868d.png">
and each time I enter any gdb command e.g. step, stepi ...., this error repeats.
How to solve this problem ?

**Comment by sbeamer** [comment]
We welcome contributions to add support for gdb. We currently do not support it.

Similar to https://github.com/riscv/homebrew-riscv/issues/26

**Comment by Kuluso97** [comment]
brew install gdb, and copy the /usr/local/Cellar/gdb/<version code>/share/gdb/python to your riscv destination directory shown in the warning. This works for me.
