### ISSUE TITLE
riscv-isa-sim build failed in macOS 10.13.6

### ISSUE THREAD

**Issue by jscode017** [riscv/homebrew-riscv#38]
==> Installing riscv/riscv/riscv-tools dependency: riscv-isa-sim
Warning: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

```
==> ../configure --prefix=/usr/local/Cellar/riscv-isa-sim/master
==> make prefix=/usr/local
Last 15 lines from /Users/jasonwang/Library/Logs/Homebrew/riscv-isa-sim/02.make:
      $_42::to_string(insn_t) const in libriscv.a(disasm.o)
      $_43::to_string(insn_t) const in libriscv.a(disasm.o)
  "_xpr_name", referenced from:
      $_1::to_string(insn_t) const in cflush.o
      $_1::to_string(insn_t) const in libriscv.a(disasm.o)
      $_2::to_string(insn_t) const in libriscv.a(disasm.o)
      $_3::to_string(insn_t) const in libriscv.a(disasm.o)
      $_4::to_string(insn_t) const in libriscv.a(disasm.o)
      $_5::to_string(insn_t) const in libriscv.a(disasm.o)
      $_6::to_string(insn_t) const in libriscv.a(disasm.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libcustomext.so] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by aswaterman** [comment]
Whoops, fixed in b1d370cb41421325a7d7da22be4a6a83aac32f55
