### ISSUE TITLE
Build Failed on M1 Macbook Air

### ISSUE THREAD

**Issue by 3SUM** [riscv/homebrew-riscv#43]
`echo timestamp > s-fixinc_list
mv tmp-libgcc.mvars libgcc.mvars
Undefined symbols for architecture arm64:
  "_host_hooks", referenced from:
      c_common_no_more_pch() in c-pch.o
      toplev::main(int, char**) in libbackend.a(toplev.o)
      gt_pch_save(__sFILE*) in libbackend.a(ggc-common.o)
      gt_pch_restore(__sFILE*) in libbackend.a(ggc-common.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [cc1] Error 1
make[2]: *** Waiting for unfinished jobs....
rm gcov.pod fsf-funding.pod lto-dump.pod gpl.pod cpp.pod gfdl.pod gcc.pod gcov-dump.pod gcov-tool.pod
make[1]: *** [all-gcc] Error 2
make: *** [stamps/build-gcc-newlib-stage1] Error 2`

When running make near the end of the installation, this error occurs.

**Comment by xhw1** [comment]
+1

**Comment by sbeamer** [comment]
Lets use #47 to track this discussion (M1 support) since that issue already has more content.
