### ISSUE TITLE
build fail on OS X Yosemite

### ISSUE THREAD

**Issue by labolas89** [riscv/homebrew-riscv#5]
hi
i install risk-tools on OS X Yosemite 10.10.5 (14F1713) with Xcode 7.2.1 (7C1002)
this is my riscv-gcc make log file
[02.make.zip](https://github.com/riscv/homebrew-riscv/files/207870/02.make.zip)

i can't upgrade to El Capitan. 
what should i do?

Thanks

**Comment by sbeamer** [comment]
Yosemite probably isn't the problem. From the error file, it is difficult to see what is going on because it is a parallel build. What happens you try to build it directly from https://github.com/riscv/riscv-gnu-toolchain/?

**Comment by sbeamer** [comment]
Please comment again to re-open this issue.
