### ISSUE TITLE
Build the linux cross compiler?

### ISSUE THREAD

**Issue by thorlucas** [riscv/homebrew-riscv#50]
This seems to only build riscv64-unknown-elf.

**Comment by sbeamer** [comment]
Yes, you are correct.

Building the linux compiler on macOS has been problematic for many years. The biggest issue is glibc needs a case sensitive file system to be built, and the default formats for macs typically are case insensitive. I haven't looked into this closely a couple years, so perhaps if we are lucky, glibc resolved this issue.

We will welcome PRs to add support for this.
