### ISSUE TITLE
While installing, package is removed from the brew tap (riscv/riscv) and brew has difficulties finding it somewhere else

### ISSUE THREAD

**Issue by SyedAliAsif** [riscv/homebrew-riscv#54]
I have added the screenshot of the error message.
![image](https://user-images.githubusercontent.com/32524118/114657690-999f3800-9cbe-11eb-9507-c4db84e666db.png)

**Comment by jleidel** [comment]
Note that this occurs on MacOS Big Sur, Version 11.2.3.

**Comment by sbeamer** [comment]
Perhaps run `brew update` and then try manually installing gawk (`brew install gawk`)?

I still see gawk as a regular package for homebrew, so I'm having trouble reproducing.
