### ISSUE TITLE
Problem on using riscv-gcc

### ISSUE THREAD

**Issue by rosegengh** [riscv/homebrew-riscv#55]
Hello to all there i'm installing the tools for RISCV on macOs Big Sur version 11.2.3:
https://github.com/riscv/homebrew-riscv
My `brew test riscv-tools' command gives me:
```
==> Testing riscv/riscv/riscv-tools
==> /usr/local/opt/riscv-gnu-toolchain/bin/riscv64-unknown-elf-gcc /private/tmp/
==> spike pk /private/tmp/riscv-tools-test-20210415-34335-kr99o9/a.out
```
I try to run riscv-gcc it showed command not found. Am I installed it correctly?

**Comment by sbeamer** [comment]
If no error messages followed that test line, then it means it was installed correctly.

The compiler is named `riscv64-unknown-elf-gcc`
