### ISSUE TITLE
riscv64-unknown-elf-gdb: Installation error: gdb._execute_unwinders function is missing

### ISSUE THREAD

**Issue by Happytreat** [riscv/homebrew-riscv#61]
Hi, I am currently work on xv6 riscv and it seems that riscv64-unknown-elf-gdb doesn't work. Could you please help me with it?

After running riscv64-unknown-elf-gdb, the ERROR message was: 

`Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing`

**.gdbinit**: (Expected to work) 
```
set confirm off
set architecture riscv:rv64
target remote 127.0.0.1:25501
symbol-file kernel/kernel
set disassemble-next-line auto
```

**Comment by sbeamer** [comment]
How are you intending to use gdb in this context? In other words, what is emulating RISC-V on your mac?

**Comment by jimizai** [comment]
I just copy the /usr/local/Cellar/gdb/10.1/share/gdb/python to the folder, looks like the problem solved.

**Comment by Smith-Cruise** [comment]
> I just copy the /usr/local/Cellar/gdb/10.1/share/gdb/python to the folder, looks like the problem solved.

Please tell me to copy to which folder, I'm facing the same problem you've met.

**Comment by Virus-V** [comment]
```
cd /usr/local/Cellar/riscv-gnu-toolchain/master/share
mkdir gdb
cd gdb
cp -r /usr/local/Cellar/gdb/10.2/share/gdb/python .
```
@Smith-Cruise Executing these commands seems to solve my problem.
