### ISSUE TITLE
Why it let me type name and password

### ISSUE THREAD

**Issue by ImAlien** [riscv/homebrew-riscv#68]
`==> Tapping riscv/risev
Cloning into '/opt/homebrew/Library/Taps/riscv/homebrew-risev'...
Username for 'https://github.com': `

**Comment by sbeamer** [comment]
It appears you might have had a typo (`risev` instead of `riscv`). When tapping, be sure to try:
```
$ brew tap riscv/riscv
```

**Comment by ImAlien** [comment]
> It appears you might have had a typo (`risev` instead of `riscv`). When tapping, be sure to try:
> 
> ```
> $ brew tap riscv/riscv
> ```

oh, thank you
